/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class TaniMainUI extends javax.swing.JFrame {
    
    private void clearForm(){
        //mengkosongkan textfield di input tab
        tf_bibitNama.setText(null);
        tf_bibitHarga.setText(null);
        tf_biayaPerawatan.setText(null);
        tf_hasilBerat.setText(null);
        tf_hasilHarga.setText(null);
    }
    
    private void showInfo(){
        //bikin tabel
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Tanaman");
        model.addColumn("Harga Bibit");
        model.addColumn("Perawatan");
        model.addColumn("Modal");
        model.addColumn("Berat (Kg)");
        model.addColumn("Harga/Kg");
        model.addColumn("Total Hasil");
        model.addColumn("Ratio Kotor");
        
        try{
            //fetch info dari tabel dbase
            String sql="SELECT nama_bibit, harga_bibit, biaya_perawatan, modal, hasil_kg, hasil_harga_kg, total_hasil, ratio_kotor FROM data_tani";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});
            }
            
            tb_dataTani.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error: "+ e.getMessage());
        }
        
    }

    /**
     * Creates new form TaniMainUI
     */
    public TaniMainUI() {
        initComponents();
        showInfo();
        clearForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_bibitNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_bibitHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_biayaPerawatan = new javax.swing.JTextField();
        tf_hasilBerat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_hasilHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jb_clear = new javax.swing.JButton();
        jb_save = new javax.swing.JButton();
        jb_update = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dataTani = new javax.swing.JTable();
        jb_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        tf_bibitNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bibitNamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Harga");

        jLabel3.setText("Biaya Perawatan");

        jLabel4.setText("Berat (Kg)");

        jLabel5.setText("Harga per Kg");

        jLabel6.setText("Bibit");

        jLabel7.setText("Hasil");

        jb_clear.setText("Clear");
        jb_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clearActionPerformed(evt);
            }
        });

        jb_save.setText("Save");
        jb_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saveActionPerformed(evt);
            }
        });

        jb_update.setText("Update");
        jb_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jb_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jb_save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jb_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_bibitHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_hasilHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_hasilBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_biayaPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_bibitNama, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_bibitNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_bibitHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_biayaPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_hasilBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_hasilHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jb_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Input UI", jPanel1);

        tb_dataTani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanaman", "Harga Bibit", "Perawatan", "Modal", "Berat (Kg)", "Harga/Kg", "Hasil", "Ratio Kotor"
            }
        ));
        tb_dataTani.setColumnSelectionAllowed(true);
        tb_dataTani.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tb_dataTaniMouseWheelMoved(evt);
            }
        });
        tb_dataTani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataTaniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dataTani);
        tb_dataTani.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jb_delete.setText("Delete");
        jb_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jb_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(609, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jb_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Info Table", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_bibitNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bibitNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bibitNamaActionPerformed

    private void jb_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clearActionPerformed
        clearForm();
    }//GEN-LAST:event_jb_clearActionPerformed

    private void tb_dataTaniMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tb_dataTaniMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_dataTaniMouseWheelMoved

    private void jb_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saveActionPerformed

        //bibit
        String bibitNama=tf_bibitNama.getText().trim();
        double bHarga=Double.valueOf(tf_bibitHarga.getText().trim());
        String bibitHarga=String.valueOf(bHarga);
        
        //biaya perawatan
        double biPerawatan=Double.valueOf(tf_biayaPerawatan.getText().trim());
        String biayaPerawatan=String.valueOf(biPerawatan);
        
        //modal
        double mdl=bHarga+biPerawatan;
        String modal=String.valueOf(mdl);
        
        //hasil
        double hBerat=Double.valueOf(tf_hasilBerat.getText().trim());
        String hasilBerat=String.valueOf(hBerat);
        double hHarga=Double.valueOf(tf_hasilHarga.getText().trim());
        String hasilHarga=String.valueOf(hHarga);
        double tHasil=hBerat+hHarga;
        String totalHasil=String.valueOf(tHasil);
        
        //rasio keuntungan kotor
        double kKotor=((tHasil-mdl)/mdl);
        String rasioKKotor=String.valueOf(kKotor);
        
        //simpan data
        try{
            String sql="INSERT INTO data_tani VALUES('"+bibitNama+"','"+bibitHarga+"','"+biayaPerawatan+"','"+modal+"','"+hasilBerat+"','"+hasilHarga+"','"+totalHasil+"','"+rasioKKotor+"')";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data successfully saved...");
            showInfo();
            clearForm();
        }catch (HeadlessException|SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_jb_saveActionPerformed

    private void tb_dataTaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataTaniMouseClicked
        //tampilkan baris yang diklik
        int row=tb_dataTani.rowAtPoint(evt.getPoint());
        String namBit=tb_dataTani.getValueAt(row, 0).toString();
        tf_bibitNama.setText(namBit);
        
        String harBit=tb_dataTani.getValueAt(row, 1).toString();
        tf_bibitHarga.setText(harBit);
        
        String biPer=tb_dataTani.getValueAt(row, 2).toString();
        tf_biayaPerawatan.setText(biPer);
        
        String hasBer=tb_dataTani.getValueAt(row, 4).toString();
        tf_hasilBerat.setText(hasBer);
        
        String hasHar=tb_dataTani.getValueAt(row, 5).toString();
        tf_hasilHarga.setText(hasHar);
    }//GEN-LAST:event_tb_dataTaniMouseClicked

    private void jb_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_deleteActionPerformed
        try{
            String sql="DELETE FROM data_tani WHERE nama_bibit='"+tf_bibitNama.getText().trim()+"'";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data successfully deleted...");
            showInfo();
            clearForm();
        }catch (HeadlessException|SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jb_deleteActionPerformed

    private void jb_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_updateActionPerformed
        //update baris yang diklik
        //bibit
        String bibitNama=tf_bibitNama.getText().trim();
        double bHarga=Double.valueOf(tf_bibitHarga.getText().trim());
        String bibitHarga=String.valueOf(bHarga);
        
        //biaya perawatan
        double biPerawatan=Double.valueOf(tf_biayaPerawatan.getText().trim());
        String biayaPerawatan=String.valueOf(biPerawatan);
        
        //modal
        double mdl=bHarga+biPerawatan;
        String modal=String.valueOf(mdl);
        
        //hasil
        double hBerat=Double.valueOf(tf_hasilBerat.getText().trim());
        String hasilBerat=String.valueOf(hBerat);
        double hHarga=Double.valueOf(tf_hasilHarga.getText().trim());
        String hasilHarga=String.valueOf(hHarga);
        double tHasil=hBerat+hHarga;
        String totalHasil=String.valueOf(tHasil);
        
        //rasio keuntungan kotor
        double kKotor=((tHasil-mdl)/mdl);
        String rasioKKotor=String.valueOf(kKotor);
        
        //update data
        try{
            String sql="UPDATE data_tani SET harga_bibit='"+bibitHarga+"', biaya_perawatan='"+biayaPerawatan+"', modal='"+modal+"', hasil_kg='"+hasilBerat+"', hasil_harga_kg='"+hasilHarga+"', total_hasil='"+totalHasil+"', ratio_kotor='"+rasioKKotor+"' WHERE nama_bibit='"+bibitNama+"'";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data successfully updated...");
            showInfo();
            clearForm();
        }catch (HeadlessException|SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jb_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaniMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaniMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaniMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaniMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaniMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_clear;
    private javax.swing.JButton jb_delete;
    private javax.swing.JButton jb_save;
    private javax.swing.JButton jb_update;
    private javax.swing.JTable tb_dataTani;
    private javax.swing.JTextField tf_biayaPerawatan;
    private javax.swing.JTextField tf_bibitHarga;
    private javax.swing.JTextField tf_bibitNama;
    private javax.swing.JTextField tf_hasilBerat;
    private javax.swing.JTextField tf_hasilHarga;
    // End of variables declaration//GEN-END:variables
}